sudo: false
language: node_js
node_js:
  - 6
env:
  global:
    - CXX=g++-4.8
    - ENCRYPTION_LABEL: "4b6d0faa79f2"
    - COMMIT_AUTHOR_EMAIL: "dtothefp@gmail.com"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - npm config set progress=false
  - npm install -g npm@^3
install:
  - npm i
before_script:
  - export REPO=`git config remote.origin.url`
  - export SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
  - echo "ssh repo: $SSH_REPO"
script:
  - npm start
  - npm run deploy
after_script:
  - npm test
